name: Build Docker

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm,arm64
      - name: Build a Docker image
        run: |
          mkdir image && cd image
          wget -q http://download.tizen.org/releases/milestone/tizen/unified/tizen-unified_20211014.1/images/standard/tizen-headed-armv7l/tizen-unified_20211014.1_tizen-headed-armv7l.tar.gz
          tar -zxf tizen-unified_20211014.1_tizen-headed-armv7l.tar.gz
          mkdir rootfs
          sudo mount rootfs.img rootfs
          sudo tar -cC rootfs . | docker import - tizen-headed-armv7l
          sudo umount rootfs
      - name: Test run
        run: docker run --rm -t tizen-headed-armv7l uname -a
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/tizen:latest
