name: release

on:
  push:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - name: create archives
        run: |
          mkdir tizen-arm-release
          mkdir tizen-arm64-unittests
          mkdir -p tizen-x86-debug/aa

          rm -rf *-unittests
          for dir in tizen-*; do
            7z a $dir.zip ./$dir/*
          done

      - name: set variables
        run: |
          echo "TAG_NAME=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
          echo "VERSION=$(echo "${{ github.ref_name }}" | cut -d'-' -f2)" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }} (${{ env.TAG_NAME }})
          tag_name: ${{ env.TAG_NAME }}
          target_commitish: ${{ github.ref_name }}
          files: ./*.zip
          body: |
            Flutter engine ${{ env.VERSION }} for Tizen

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
