name: test

on:
  push:
  workflow_dispatch:

jobs:
  run-unittests:
    name: armv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo apt update
          sudo apt install qemu binfmt-support qemu-user-static
      - name: Run
        run: |
          docker run --rm -t arm64v8/ubuntu uname -a
