name: test

on:
  push:
  workflow_dispatch:

jobs:
  run-unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l, aarch64]
    env:
      NAME: tizen-headed-{{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm,arm64
      - name: Build Docker images
        env:
          REPO_URL: http://download.tizen.org/releases/milestone/tizen/unified
          OBS_ID: tizen-unified_20211014.1
        run: |
          mkdir tmp && cd tmp
          wget -q ${REPO_URL}/${OBS_ID}/images/standard/${NAME}/${OBS_ID}_${NAME}.tar.gz
          tar -zxf ${OBS_ID}_${NAME}.tar.gz
          mkdir rootfs
          sudo mount rootfs.img rootfs
          sudo tar -cC rootfs . | docker import - ${NAME}
          sudo umount rootfs
      - name: Run
        run: |
          docker run --rm -t rootfs uname -a
          docker run --rm -t -v `pwd`:/engine ${NAME} /engine/flutter_tizen_unittests
