name: test

on:
  # push:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
      REPO_URL: http://download.tizen.org/releases/milestone/tizen/unified
      BUILD_ID: tizen-unified_20211014.1
      IMAGE: tizen-headed-aarch64
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          wget -q ${REPO_URL}/${BUILD_ID}/images/standard/${IMAGE}/${BUILD_ID}_${IMAGE}.tar.gz
          tar -zxf ${BUILD_ID}_${IMAGE}.tar.gz
          mkdir rootfs
          sudo mount rootfs.img rootfs
          sudo tar -cC rootfs . | docker import - ${IMAGE}
          sudo umount rootfs
      - name: Push image
        run: |
          docker tag ${IMAGE}:latest ghcr.io/swift-kim/${IMAGE}:latest
          docker push ghcr.io/swift-kim/${IMAGE}:latest

  run-tests:
    needs: build-docker
    runs-on: ubuntu-latest
    env:
      TAG: ghcr.io/swift-kim/tizen-headed-aarch64
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Run unittests
        run: |
          docker pull ${TAG}:latest
          docker run --rm -t -v `pwd`:/root ${TAG} /root/flutter_tizen_unittests
